// Generated by ReScript, PLEASE EDIT WITH CARE


let navigation = document.getElementById("navigation");

let main = document.getElementById("main");

function replaceMain(html) {
  main.setHTMLUnsafe(html);
}

export {
  navigation,
  main,
  replaceMain,
}
/* navigation Not a pure module */
