// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./html.res.js";

Html.navigation.setHTMLUnsafe("\n    <a href=\"/\">Home</a>\n    <a href=\"/one\">One</a>\n    <a href=\"/two\">Two</a>\n");

let match = location.pathname;

let tmp;

switch (match) {
  case "/" :
    tmp = import("./home.res.js").then(m => m.render);
    break;
  case "/one" :
    tmp = import("./one.res.js").then(m => m.render);
    break;
  case "/two" :
    tmp = import("./two.res.js").then(m => m.render);
    break;
  default:
    tmp = import("./fourOhFour.res.js").then(m => m.render);
}

tmp.then(render => render());

/*  Not a pure module */
