// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./html.res.js";

function render() {
  Html.replaceMain("\n        <h1>One</h1>\n        <p>This is page one</p>\n    ");
}

export {
  render,
}
/* Html Not a pure module */
