// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./html.res.js";

function render() {
  Html.replaceMain("\n        <h1>Two</h1>\n        <p>This is page Two</p>\n    ");
}

export {
  render,
}
/* Html Not a pure module */
